# Generated by Django 4.1.7 on 2023-03-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('join_date', models.DateTimeField()),
            ],
        ),
    ]
